# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\ProductionInfoRegister\ProdctionInfoRegister.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 608)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setToolTip("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 591, 571))
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 400))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 20, 551, 561))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineEdit_9)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setMinimumSize(QtCore.QSize(1000, 1000))
        self.tab_2.setAutoFillBackground(False)
        self.tab_2.setObjectName("tab_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setGeometry(QtCore.QRect(5, 0, 581, 541))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(570, 400))
        self.scrollArea.setAcceptDrops(False)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -776, 562, 1323))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(500, 1323))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 551, 831))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(9, 14, 14, 0)
        self.formLayout_2.setHorizontalSpacing(7)
        self.formLayout_2.setObjectName("formLayout_2")
        self.fileSNameLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.fileSNameLabel.setObjectName("fileSNameLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fileSNameLabel)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.LE_SMIC_Prod_ID = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_SMIC_Prod_ID.setInputMask("")
        self.LE_SMIC_Prod_ID.setObjectName("LE_SMIC_Prod_ID")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LE_SMIC_Prod_ID)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.LE_Tester_Directory = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Tester_Directory.setObjectName("LE_Tester_Directory")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LE_Tester_Directory)
        self.label100 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label100.setObjectName("label100")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label100)
        self.LE_Test_Program_Directory = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Test_Program_Directory.setObjectName("LE_Test_Program_Directory")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.LE_Test_Program_Directory)
        self.PB_Probe_Card_Setup_Name = QtWidgets.QPushButton(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PB_Probe_Card_Setup_Name.sizePolicy().hasHeightForWidth())
        self.PB_Probe_Card_Setup_Name.setSizePolicy(sizePolicy)
        self.PB_Probe_Card_Setup_Name.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PB_Probe_Card_Setup_Name.setFont(font)
        self.PB_Probe_Card_Setup_Name.setObjectName("PB_Probe_Card_Setup_Name")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.PB_Probe_Card_Setup_Name)
        self.LE_Probe_Card_Setup_Name = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Probe_Card_Setup_Name.setObjectName("LE_Probe_Card_Setup_Name")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.LE_Probe_Card_Setup_Name)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.CB_Notch_side = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.CB_Notch_side.setObjectName("CB_Notch_side")
        self.CB_Notch_side.addItem("")
        self.CB_Notch_side.addItem("")
        self.CB_Notch_side.addItem("")
        self.CB_Notch_side.addItem("")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.CB_Notch_side)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.CB_Switch_Notch = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.CB_Switch_Notch.setObjectName("CB_Switch_Notch")
        self.CB_Switch_Notch.addItem("")
        self.CB_Switch_Notch.addItem("")
        self.CB_Switch_Notch.addItem("")
        self.CB_Switch_Notch.addItem("")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.CB_Switch_Notch)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.LE_Grid_Xmax = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Grid_Xmax.setObjectName("LE_Grid_Xmax")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.LE_Grid_Xmax)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.LE_Grid_Ymax = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Grid_Ymax.setObjectName("LE_Grid_Ymax")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.LE_Grid_Ymax)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.LE_Grid_Xmin = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Grid_Xmin.setObjectName("LE_Grid_Xmin")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.LE_Grid_Xmin)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.LE_Grid_Ymin = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Grid_Ymin.setObjectName("LE_Grid_Ymin")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.LE_Grid_Ymin)
        self.shift_XLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.shift_XLabel.setObjectName("shift_XLabel")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.shift_XLabel)
        self.LE_shift_X = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_shift_X.setObjectName("LE_shift_X")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.LE_shift_X)
        self.shift_YLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.shift_YLabel.setObjectName("shift_YLabel")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.shift_YLabel)
        self.LE_shift_Y = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_shift_Y.setObjectName("LE_shift_Y")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.LE_shift_Y)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.LE_Fab_Site = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Fab_Site.setObjectName("LE_Fab_Site")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.LE_Fab_Site)
        self.test_SiteLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.test_SiteLabel.setObjectName("test_SiteLabel")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.test_SiteLabel)
        self.LE_Test_Site = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Test_Site.setObjectName("LE_Test_Site")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.LE_Test_Site)
        self.probe_Card_IDLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.probe_Card_IDLabel.setObjectName("probe_Card_IDLabel")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.probe_Card_IDLabel)
        self.LE_Probe_Card_ID = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Probe_Card_ID.setObjectName("LE_Probe_Card_ID")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.LE_Probe_Card_ID)
        self.wM_ORIGINLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.wM_ORIGINLabel.setObjectName("wM_ORIGINLabel")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.wM_ORIGINLabel)
        self.LE_WM_ORIGIN = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_WM_ORIGIN.setObjectName("LE_WM_ORIGIN")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.LE_WM_ORIGIN)
        self.load_Board_IDLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.load_Board_IDLabel.setObjectName("load_Board_IDLabel")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.load_Board_IDLabel)
        self.LE_Load_Board_ID = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Load_Board_ID.setObjectName("LE_Load_Board_ID")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.LE_Load_Board_ID)
        self.rOM_CodeLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.rOM_CodeLabel.setObjectName("rOM_CodeLabel")
        self.formLayout_2.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.rOM_CodeLabel)
        self.LE_ROM_Code = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_ROM_Code.setObjectName("LE_ROM_Code")
        self.formLayout_2.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.LE_ROM_Code)
        self.xDieSizeLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.xDieSizeLabel.setObjectName("xDieSizeLabel")
        self.formLayout_2.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.xDieSizeLabel)
        self.LE_X_Die_Size = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_X_Die_Size.setObjectName("LE_X_Die_Size")
        self.formLayout_2.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.LE_X_Die_Size)
        self.yDieSizeLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.yDieSizeLabel.setObjectName("yDieSizeLabel")
        self.formLayout_2.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.yDieSizeLabel)
        self.LE_Y_Die_Size = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Y_Die_Size.setObjectName("LE_Y_Die_Size")
        self.formLayout_2.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.LE_Y_Die_Size)
        self.x_StreetLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.x_StreetLabel.setObjectName("x_StreetLabel")
        self.formLayout_2.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.x_StreetLabel)
        self.LE_X_Street = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_X_Street.setObjectName("LE_X_Street")
        self.formLayout_2.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.LE_X_Street)
        self.y_StreetLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.y_StreetLabel.setObjectName("y_StreetLabel")
        self.formLayout_2.setWidget(23, QtWidgets.QFormLayout.LabelRole, self.y_StreetLabel)
        self.LE_Y_Street = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Y_Street.setObjectName("LE_Y_Street")
        self.formLayout_2.setWidget(23, QtWidgets.QFormLayout.FieldRole, self.LE_Y_Street)
        self.customer_CodeLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.customer_CodeLabel.setObjectName("customer_CodeLabel")
        self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.LabelRole, self.customer_CodeLabel)
        self.LE_Customer_Code = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Customer_Code.setObjectName("LE_Customer_Code")
        self.formLayout_2.setWidget(24, QtWidgets.QFormLayout.FieldRole, self.LE_Customer_Code)
        self.customer_PartIDLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.customer_PartIDLabel.setObjectName("customer_PartIDLabel")
        self.formLayout_2.setWidget(25, QtWidgets.QFormLayout.LabelRole, self.customer_PartIDLabel)
        self.LE_Customer_PartID = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Customer_PartID.setObjectName("LE_Customer_PartID")
        self.formLayout_2.setWidget(25, QtWidgets.QFormLayout.FieldRole, self.LE_Customer_PartID)
        self.gross_DieLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.gross_DieLabel.setObjectName("gross_DieLabel")
        self.formLayout_2.setWidget(26, QtWidgets.QFormLayout.LabelRole, self.gross_DieLabel)
        self.LE_Gross_Die = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Gross_Die.setObjectName("LE_Gross_Die")
        self.formLayout_2.setWidget(26, QtWidgets.QFormLayout.FieldRole, self.LE_Gross_Die)
        self.gross_DieLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.gross_DieLabel_2.setObjectName("gross_DieLabel_2")
        self.formLayout_2.setWidget(27, QtWidgets.QFormLayout.LabelRole, self.gross_DieLabel_2)
        self.LE_Prr_Check_Number = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Prr_Check_Number.setObjectName("LE_Prr_Check_Number")
        self.formLayout_2.setWidget(27, QtWidgets.QFormLayout.FieldRole, self.LE_Prr_Check_Number)
        self.magnum_UI_VersionLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.magnum_UI_VersionLabel.setObjectName("magnum_UI_VersionLabel")
        self.formLayout_2.setWidget(28, QtWidgets.QFormLayout.LabelRole, self.magnum_UI_VersionLabel)
        self.LE_Magnum_UI_Version = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Magnum_UI_Version.setObjectName("LE_Magnum_UI_Version")
        self.formLayout_2.setWidget(28, QtWidgets.QFormLayout.FieldRole, self.LE_Magnum_UI_Version)
        self.datalog_SetupLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.datalog_SetupLabel.setObjectName("datalog_SetupLabel")
        self.formLayout_2.setWidget(29, QtWidgets.QFormLayout.LabelRole, self.datalog_SetupLabel)
        self.LE_Datalog_Setup = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_Datalog_Setup.setObjectName("LE_Datalog_Setup")
        self.formLayout_2.setWidget(29, QtWidgets.QFormLayout.FieldRole, self.LE_Datalog_Setup)
        self.releaseTesterLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.releaseTesterLabel.setObjectName("releaseTesterLabel")
        self.formLayout_2.setWidget(30, QtWidgets.QFormLayout.LabelRole, self.releaseTesterLabel)
        self.LE_ReleaseTester = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_ReleaseTester.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LE_ReleaseTester.setObjectName("LE_ReleaseTester")
        self.formLayout_2.setWidget(30, QtWidgets.QFormLayout.FieldRole, self.LE_ReleaseTester)
        self.serverDirectoryLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.serverDirectoryLabel.setObjectName("serverDirectoryLabel")
        self.formLayout_2.setWidget(31, QtWidgets.QFormLayout.LabelRole, self.serverDirectoryLabel)
        self.LE_ServerDirectory = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.LE_ServerDirectory.setObjectName("LE_ServerDirectory")
        self.formLayout_2.setWidget(31, QtWidgets.QFormLayout.FieldRole, self.LE_ServerDirectory)
        self.fileSNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.fileSNameLineEdit.setObjectName("fileSNameLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileSNameLineEdit)
        self.BTN_Create = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.BTN_Create.setGeometry(QtCore.QRect(470, 1270, 75, 23))
        self.BTN_Create.setObjectName("BTN_Create")
        self.BTN_Clear = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.BTN_Clear.setGeometry(QtCore.QRect(380, 1270, 75, 23))
        self.BTN_Clear.setObjectName("BTN_Clear")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(10, 830, 551, 421))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(True)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(240, 160, 281, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_Update = QtWidgets.QPushButton(self.layoutWidget)
        self.PB_Update.setObjectName("PB_Update")
        self.horizontalLayout.addWidget(self.PB_Update)
        self.PB_Modify = QtWidgets.QPushButton(self.layoutWidget)
        self.PB_Modify.setObjectName("PB_Modify")
        self.horizontalLayout.addWidget(self.PB_Modify)
        self.PB__delete = QtWidgets.QPushButton(self.layoutWidget)
        self.PB__delete.setObjectName("PB__delete")
        self.horizontalLayout.addWidget(self.PB__delete)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 531, 157))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setContentsMargins(8, 5, 10, 10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.sortLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.sortLabel_2.setObjectName("sortLabel_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sortLabel_2)
        self.sortLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.sortLineEdit_2.setObjectName("sortLineEdit_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sortLineEdit_2)
        self.testflowLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.testflowLabel_2.setObjectName("testflowLabel_2")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.testflowLabel_2)
        self.packageLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.packageLineEdit_2.setObjectName("packageLineEdit_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.packageLineEdit_2)
        self.programNameLabel_2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.programNameLabel_2.setObjectName("programNameLabel_2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.programNameLabel_2)
        self.programNameLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.programNameLineEdit_2.setReadOnly(True)
        self.programNameLineEdit_2.setObjectName("programNameLineEdit_2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.programNameLineEdit_2)
        self.binDefinationLineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.binDefinationLineEdit_2.setObjectName("binDefinationLineEdit_2")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.binDefinationLineEdit_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.PB_Package = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.PB_Package.setObjectName("PB_Package")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.PB_Package)
        self.PB_BinDef = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.PB_BinDef.setObjectName("PB_BinDef")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.PB_BinDef)
        self.Table1 = QtWidgets.QTableWidget(self.groupBox)
        self.Table1.setGeometry(QtCore.QRect(10, 200, 521, 211))
        self.Table1.setMouseTracking(False)
        self.Table1.setTabletTracking(False)
        self.Table1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Table1.setObjectName("Table1")
        self.Table1.setColumnCount(5)
        self.Table1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Table1.setHorizontalHeaderItem(4, item)
        self.Table1.horizontalHeader().setDefaultSectionSize(101)
        self.Table1.horizontalHeader().setMinimumSectionSize(15)
        self.Table1.verticalHeader().setDefaultSectionSize(40)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 600, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuUser = QtWidgets.QMenu(self.menuBar)
        self.menuUser.setObjectName("menuUser")
        self.menuLog_in = QtWidgets.QMenu(self.menuUser)
        self.menuLog_in.setObjectName("menuLog_in")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menuBar)
        self.actionLog_out = QtWidgets.QAction(MainWindow)
        self.actionLog_out.setObjectName("actionLog_out")
        self.actionFor_SE = QtWidgets.QAction(MainWindow)
        self.actionFor_SE.setObjectName("actionFor_SE")
        self.actionFor_Vender = QtWidgets.QAction(MainWindow)
        self.actionFor_Vender.setObjectName("actionFor_Vender")
        self.actionVersion = QtWidgets.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionCheck_Update = QtWidgets.QAction(MainWindow)
        self.actionCheck_Update.setObjectName("actionCheck_Update")
        self.actionClear_All = QtWidgets.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.actionProduction_Load_File = QtWidgets.QAction(MainWindow)
        self.actionProduction_Load_File.setObjectName("actionProduction_Load_File")
        self.actionSWT_File = QtWidgets.QAction(MainWindow)
        self.actionSWT_File.setObjectName("actionSWT_File")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPath_Configre = QtWidgets.QAction(MainWindow)
        self.actionPath_Configre.setObjectName("actionPath_Configre")
        self.actionroot = QtWidgets.QAction(MainWindow)
        self.actionroot.setObjectName("actionroot")
        self.menuLog_in.addAction(self.actionFor_SE)
        self.menuLog_in.addAction(self.actionFor_Vender)
        self.menuLog_in.addSeparator()
        self.menuLog_in.addAction(self.actionroot)
        self.menuUser.addAction(self.menuLog_in.menuAction())
        self.menuUser.addAction(self.actionLog_out)
        self.menuUser.addSeparator()
        self.menuHelp.addAction(self.actionPath_Configre)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionCheck_Update)
        self.menuHelp.addAction(self.actionVersion)
        self.menuOpen.addAction(self.actionProduction_Load_File)
        self.menuOpen.addAction(self.actionSWT_File)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.actionClear_All)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuUser.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label_10.setBuddy(self.LE_SMIC_Prod_ID)
        self.label_11.setBuddy(self.LE_Tester_Directory)
        self.label_15.setBuddy(self.LE_Grid_Xmax)
        self.label_16.setBuddy(self.LE_Grid_Ymax)
        self.label_18.setBuddy(self.LE_Grid_Ymin)
        self.label_19.setBuddy(self.LE_Grid_Ymin)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ProductionInfoRegister"))
        MainWindow.setStatusTip(_translate("MainWindow", "Please Sign In First!!!"))
        self.label.setText(_translate("MainWindow", "CUSTOMER"))
        self.label_2.setText(_translate("MainWindow", "PRODUCT_NAME"))
        self.label_3.setText(_translate("MainWindow", "PRODUCT_CODE"))
        self.label_4.setText(_translate("MainWindow", "GROSS_DIE"))
        self.label_5.setText(_translate("MainWindow", "YIELD_LIMIT"))
        self.label_6.setText(_translate("MainWindow", "INDEX_MSEC"))
        self.label_7.setText(_translate("MainWindow", "DUTS_DIFF"))
        self.label_8.setText(_translate("MainWindow", "MAGNUM_SITE_NUMBER"))
        self.label_9.setText(_translate("MainWindow", "TOTAL_DIE_ACCOUNT"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "SWT Creator"))
        self.fileSNameLabel.setText(_translate("MainWindow", "File\'s Name"))
        self.label_10.setText(_translate("MainWindow", "SMIC_Prod_ID"))
        self.LE_SMIC_Prod_ID.setPlaceholderText(_translate("MainWindow", "ProductID-Version-Gross_site"))
        self.label_11.setText(_translate("MainWindow", "Tester_Directory"))
        self.LE_Tester_Directory.setText(_translate("MainWindow", "C:\\nextest\\_production\\tester"))
        self.label100.setText(_translate("MainWindow", "Test_Program_Directory"))
        self.LE_Test_Program_Directory.setText(_translate("MainWindow", "D:\\TestProgram"))
        self.PB_Probe_Card_Setup_Name.setText(_translate("MainWindow", "Probe_Card_Setup_Name"))
        self.LE_Probe_Card_Setup_Name.setPlaceholderText(_translate("MainWindow", "XXXXXX.swt"))
        self.label_13.setText(_translate("MainWindow", "Notch_side"))
        self.CB_Notch_side.setItemText(0, _translate("MainWindow", "D"))
        self.CB_Notch_side.setItemText(1, _translate("MainWindow", "R"))
        self.CB_Notch_side.setItemText(2, _translate("MainWindow", "L"))
        self.CB_Notch_side.setItemText(3, _translate("MainWindow", "D"))
        self.label_14.setText(_translate("MainWindow", "Switch_Notch"))
        self.CB_Switch_Notch.setItemText(0, _translate("MainWindow", "0"))
        self.CB_Switch_Notch.setItemText(1, _translate("MainWindow", "90"))
        self.CB_Switch_Notch.setItemText(2, _translate("MainWindow", "180"))
        self.CB_Switch_Notch.setItemText(3, _translate("MainWindow", "270"))
        self.label_15.setText(_translate("MainWindow", "Grid_Xmax"))
        self.LE_Grid_Xmax.setPlaceholderText(_translate("MainWindow", "Maximal number of X-Coordinate"))
        self.label_16.setText(_translate("MainWindow", "Grid_Ymax"))
        self.LE_Grid_Ymax.setPlaceholderText(_translate("MainWindow", "Maximal number of Y-Coordinate"))
        self.label_17.setText(_translate("MainWindow", "Grid_Xmin"))
        self.LE_Grid_Xmin.setPlaceholderText(_translate("MainWindow", "Minimal number of X-Coordinate"))
        self.label_18.setText(_translate("MainWindow", "Grid_Ymin"))
        self.LE_Grid_Ymin.setPlaceholderText(_translate("MainWindow", "Minimal number of Y-Coordinate"))
        self.shift_XLabel.setText(_translate("MainWindow", "shift_X"))
        self.LE_shift_X.setPlaceholderText(_translate("MainWindow", "Number"))
        self.shift_YLabel.setText(_translate("MainWindow", "shift_Y"))
        self.LE_shift_Y.setPlaceholderText(_translate("MainWindow", "Number"))
        self.label_19.setText(_translate("MainWindow", "Fab_Site"))
        self.LE_Fab_Site.setText(_translate("MainWindow", "SMICFAB2"))
        self.test_SiteLabel.setText(_translate("MainWindow", "Test_Site"))
        self.LE_Test_Site.setText(_translate("MainWindow", "SMICTEST"))
        self.probe_Card_IDLabel.setText(_translate("MainWindow", "Probe_Card_ID"))
        self.LE_Probe_Card_ID.setPlaceholderText(_translate("MainWindow", "PC_ID1, PC_ID2"))
        self.wM_ORIGINLabel.setText(_translate("MainWindow", "WM_ORIGIN"))
        self.LE_WM_ORIGIN.setText(_translate("MainWindow", "TOP_LEFT"))
        self.load_Board_IDLabel.setText(_translate("MainWindow", "Load_Board_ID"))
        self.LE_Load_Board_ID.setPlaceholderText(_translate("MainWindow", "LoadBoardID1, LoadBordID2"))
        self.rOM_CodeLabel.setText(_translate("MainWindow", "ROM_Code"))
        self.LE_ROM_Code.setPlaceholderText(_translate("MainWindow", "CHK|||||||||||||||8576-2|"))
        self.xDieSizeLabel.setText(_translate("MainWindow", "X Die Size"))
        self.LE_X_Die_Size.setPlaceholderText(_translate("MainWindow", "????UM"))
        self.yDieSizeLabel.setText(_translate("MainWindow", "Y Die Size"))
        self.LE_Y_Die_Size.setPlaceholderText(_translate("MainWindow", "????UM"))
        self.x_StreetLabel.setText(_translate("MainWindow", "X_Street"))
        self.LE_X_Street.setPlaceholderText(_translate("MainWindow", "Number"))
        self.y_StreetLabel.setText(_translate("MainWindow", "Y_Street"))
        self.LE_Y_Street.setPlaceholderText(_translate("MainWindow", "Number"))
        self.customer_CodeLabel.setText(_translate("MainWindow", "Customer_Code"))
        self.LE_Customer_Code.setPlaceholderText(_translate("MainWindow", "S048-C02"))
        self.customer_PartIDLabel.setText(_translate("MainWindow", "Customer_PartID"))
        self.LE_Customer_PartID.setPlaceholderText(_translate("MainWindow", "Customer device name"))
        self.gross_DieLabel.setText(_translate("MainWindow", "Gross_Die"))
        self.LE_Gross_Die.setPlaceholderText(_translate("MainWindow", "Number"))
        self.gross_DieLabel_2.setText(_translate("MainWindow", "Prr_Check_Number"))
        self.LE_Prr_Check_Number.setPlaceholderText(_translate("MainWindow", "Number"))
        self.magnum_UI_VersionLabel.setText(_translate("MainWindow", "Magnum_UI_Version"))
        self.LE_Magnum_UI_Version.setText(_translate("MainWindow", "h4.3.0.4"))
        self.datalog_SetupLabel.setText(_translate("MainWindow", "Datalog_Setup"))
        self.LE_Datalog_Setup.setText(_translate("MainWindow", "C:\\nextest\\_production\\datalog_setup"))
        self.releaseTesterLabel.setText(_translate("MainWindow", "ReleaseTester"))
        self.LE_ReleaseTester.setPlaceholderText(_translate("MainWindow", "1HTM202"))
        self.serverDirectoryLabel.setText(_translate("MainWindow", "ServerDirectory"))
        self.LE_ServerDirectory.setText(_translate("MainWindow", "Z:\\SMIC\\Testing\\TDS\\share\\production\\rawdata"))
        self.fileSNameLineEdit.setPlaceholderText(_translate("MainWindow", "ProductionLoaderFileName"))
        self.BTN_Create.setText(_translate("MainWindow", "Create"))
        self.BTN_Clear.setText(_translate("MainWindow", "Clear"))
        self.groupBox.setTitle(_translate("MainWindow", "TP Control Group"))
        self.PB_Update.setText(_translate("MainWindow", "Update"))
        self.PB_Modify.setText(_translate("MainWindow", "Modify"))
        self.PB__delete.setText(_translate("MainWindow", "Delete"))
        self.sortLabel_2.setText(_translate("MainWindow", "Sort"))
        self.testflowLabel_2.setText(_translate("MainWindow", "Testflow"))
        self.programNameLabel_2.setText(_translate("MainWindow", "Program Name"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Contact"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "CP0"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "CP1"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "CP2"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "CP3"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "CP4"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "CP5"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "CP6"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "CP7"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "CP8"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "CP9"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "CP10"))
        self.comboBox_2.setItemText(13, _translate("MainWindow", "CP11"))
        self.comboBox_2.setItemText(14, _translate("MainWindow", "CP12"))
        self.PB_Package.setText(_translate("MainWindow", "Package"))
        self.PB_BinDef.setText(_translate("MainWindow", "Bin Defination"))
        item = self.Table1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sort"))
        item = self.Table1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tester flow"))
        item = self.Table1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Packge"))
        item = self.Table1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Program Name"))
        item = self.Table1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Bin Defination"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Production Loader Creator"))
        self.menuUser.setTitle(_translate("MainWindow", "User"))
        self.menuLog_in.setTitle(_translate("MainWindow", "Log in"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.actionLog_out.setText(_translate("MainWindow", "Log out"))
        self.actionFor_SE.setText(_translate("MainWindow", "For SE"))
        self.actionFor_Vender.setText(_translate("MainWindow", "For Vender"))
        self.actionVersion.setText(_translate("MainWindow", "Version"))
        self.actionCheck_Update.setText(_translate("MainWindow", "Check Update"))
        self.actionClear_All.setText(_translate("MainWindow", "Clear All"))
        self.actionProduction_Load_File.setText(_translate("MainWindow", "Production Load File"))
        self.actionSWT_File.setText(_translate("MainWindow", "SWT File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionPath_Configre.setText(_translate("MainWindow", "Path Configre"))
        self.actionroot.setText(_translate("MainWindow", "Root"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

