// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _SUBROUTINE_H_
#define _SUBROUTINE_H_

EXTERN_PATTERN( SUB_GPIB5_send_A_Byte )
EXTERN_PATTERN( SUB_GPIB5_read_A_Byte )
EXTERN_PATTERN( SUB_WaitFor_CRC )
EXTERN_PATTERN( SUB_read_CRC )

#endif
