// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _PATTERN_H_
#define _PATTERN_H_

EXTERN_PATTERN( p_ChipErase )
EXTERN_PATTERN( p_GangCKBD )
EXTERN_PATTERN( p_Dignal )
EXTERN_PATTERN( p_Pro_line )
EXTERN_PATTERN( p_SG )
EXTERN_PATTERN( p_Sec_Erase )
EXTERN_PATTERN( p_Sec_Erase_wholechip )
EXTERN_PATTERN( p_ProAll0 )
EXTERN_PATTERN( p_ExtSec_erase )
EXTERN_PATTERN( p_ExtChip_Erase )
EXTERN_PATTERN( p_ExtChip_Erase_p15ms )
EXTERN_PATTERN( p_BL_stress )
EXTERN_PATTERN( Fast_Program_CKB )
EXTERN_PATTERN( page_ChipErase_NVR0 )
EXTERN_PATTERN( Byte_Program_CKB_nvr0 )
EXTERN_PATTERN( p_ExtChip_Erase_nvr0 )

#endif
