// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _READ_H_
#define _READ_H_

EXTERN_PATTERN( p_Rd )
EXTERN_PATTERN( p_RdCKBD )
EXTERN_PATTERN( p_MRD )
EXTERN_PATTERN( p_RdDiag )
EXTERN_PATTERN( p_Rd_line )
EXTERN_PATTERN( p_RdCKBD1 )
EXTERN_PATTERN( p_RdCKBD0 )
EXTERN_PATTERN( Fast_Readff_CKB )
EXTERN_PATTERN( Fast_Read00_CKB )
EXTERN_PATTERN( p_Rd_nvr0 )
EXTERN_PATTERN( Byte_Read00_CKB_nvr0 )
EXTERN_PATTERN( Byte_Readff_CKB_nvr0 )

#endif
