// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _SUBPATTERN_H_
#define _SUBPATTERN_H_

EXTERN_PATTERN( sub_wait_50us )
EXTERN_PATTERN( sub_wait_100us )
EXTERN_PATTERN( sub_wait_5600us )
EXTERN_PATTERN( sub_wait_time )
EXTERN_PATTERN( sub_xaddr_inc )
EXTERN_PATTERN( sub_wait_1sec )
EXTERN_PATTERN( sub_powr_on )

#endif
