// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _TRIM_H_
#define _TRIM_H_

EXTERN_PATTERN( BG_Trim )
EXTERN_PATTERN( OSC_Trim_72 )
EXTERN_PATTERN( VR16_trim )
EXTERN_PATTERN( PGVPP_tirm )
EXTERN_PATTERN( PGVNN_tirm )
EXTERN_PATTERN( ERVPP_tirm )
EXTERN_PATTERN( ERVNN_tirm )
EXTERN_PATTERN( IREF_tirm )

#endif
