#ifndef _USER_VAR_H
#define _USER_VAR_H
EXTERN_CSTRING_VARIABLE(CASE_FOLDER);
EXTERN_BOOL_VARIABLE(UI_CREATE_DATALOG_FILE_FLAG);
EXTERN_BOOL_VARIABLE(UI_DATALOG_SITE);
EXTERN_BOOL_VARIABLE(UI_DATALOG_HOST); 
EXTERN_INT_VARIABLE(PRTF_COUNTER);

#endif 