#ifndef _MAGNUM_OI_H_
#define _MAGNUM_OI_H_
EXTERN_BOOL_VARIABLE( bProgLoaded)
EXTERN_BOOL_VARIABLE( bDriverLoaded)

EXTERN_VOID_VARIABLE ( cExitDlg ) 

EXTERN_INT_VARIABLE ( OI_SITE_NUM ) 
EXTERN_INT_VARIABLE ( MAX_SITES_NUM )

#endif