//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Script1.rc
//
#define IDB_BITMAP1                     107
#define IDB_BITMAP2                     112
#define IDC_KYEC_LOT_NUM                1001
#define IDC_TESTER_ID                   1002
#define IDC_START_AUTO_PROBE            1003
#define IDC_PRD_FILENAME                1003
#define IDC_STOP_AUTO_PROBE             1004
#define IDC_LOAD_BUTTON                 1005
#define IDC_FLOW_NUM                    1006
#define IDC_OPERATOR_ID                 1007
#define IDC_PROGRAM_NAME                1008
#define IDC_PAUSE                       1009
#define IDC_RESET_BUTTON                1010
#define IDC_DATALOG_BUTTON              1011
#define IDC_DATALOG_SETUP               1011
#define IDC_ENGR_LOGIN_BUTTON           1012
#define IDC_DLL_NAME                    1012
#define IDC_CHECK_FK1                   1013
#define IDC_HIDDEN                      1014
#define IDC_SWT_NAME                    1015
#define IDC_CHECK_FK2                   1016
#define IDC_CHECK_FK3                   1017
#define IDC_CHECK_FK4                   1018
#define IDC_CHECK_FK5                   1019
#define IDC_CHECK_FK6                   1020
#define IDC_DEVICE_NAME                 1022
#define IDC_CHECK_FK7                   1023
#define IDC_CHECK_FK8                   1024
#define IDC_PASSWORD                    1026
#define IDC_CHECK_FK9                   1033
#define IDC_CHECK_FK10                  1034
#define IDC_STATIC_OMS4                 1035
#define IDC_CHECK_FK11                  1035
#define IDC_CHECK_FK12                  1036
#define IDC_CHECK_FK13                  1037
#define IDC_CHECK_FK14                  1038
#define IDC_CHECK_FK15                  1039
#define IDC_CHECK_FK16                  1040
#define IDC_PRG_OPEN                    1041
#define IDC_PGMGET_BUTTON               1042
#define IDC_DLL_OPEN                    1042
#define IDC_SWT_OPEN                    1043
#define IDC_LOT_NUM                     1061
#define IDC_FLOW_NAME                   1069
#define IDC_COMMENTS                    1070
#define IDC_USER_C                      1071
#define IDC_PROBE_CARD_ID               1072
#define IDC_LATEST_WAFER_NUM            1073
#define IDC_STATUS_WAFERS               1074
#define IDC_TOUCHDOWNS                  1075
#define IDC_STATIC_2_2                  1076
#define IDC_RADIO1                      1081
#define IDC_RADIO9                      1081
#define IDC_RADIO2                      1082
#define IDC_RADIO10                     1082
#define IDC_DATALOG_SHMOO               1085
#define IDC_DATALOG_SEARCH              1086
#define IDC_DATALOG_VEC_CNT             1087
#define IDC_RADIO4                      1088
#define IDC_DATALOG_LVM                 1089
#define IDC_RADIO5                      1090
#define IDC_RADIO6                      1091
#define IDC_RADIO7                      1092
#define IDC_RADIO8                      1093
#define ID_WAFERLOAD                    1094
#define ID_WAFERUNLOAD                  1095
#define IDC_DRIVER_DLL                  1095
#define IDC_SWT                         1096
#define ID_ZUP                          1096
#define IDC_SELECT_TEST_PROGRAM         1097
#define ID_ZDOWN                        1097
#define ID_MOVE                         1098
#define IDC_RADIO11                     1099
#define IDC_RADIO12                     1100
#define IDC_DATALOG_ALL                 1101
#define IDC_X                           1101
#define IDC_DATALOG_PARA                1102
#define IDC_DATALOG_FUNC                1103
#define IDC_DATALOG_USER                1104
#define IDC_DATALOG_FILE                1105
#define IDC_Y                           1107
#define IDC_MOVE_TO_FIRST_DIE           1109
#define IDC_STDF_ENABLE                 1111
#define IDC_PRODUCT_SETUP               1112
#define IDC_PRODUCT_ID_CHECK            1112
#define IDC_LOT_ID_CHECK                1113
#define IDC_LOT_ID                      1114
#define IDC_TEST_PROGRAM_CHECK          1114
#define IDC_PROBECARD_ID                1115
#define IDC_RUNMODESELECTED_CHECK       1115
#define IDC_LOT_ID2                     1116
#define IDC_PROBECARD_ID_CHECK          1116
#define IDC_OPERATOR_ID_CHECK2          1117
#define IDC_OPERATOR_ID_CHECK           1117
#define IDC_PRODUCT_ID                  1118
#define IDC_SORT_ID                     1119
#define IDC_TEST_PROGRAM                1120
#define IDC_PROBER                      1122
#define IDC_TEST_PROGRAM_OUTPUT         1123
#define IDC_STATUS                      1124
#define IDC_PROBER_LOT_ID               1125
#define IDC_START_TIME                  1126
#define IDC_WAFER_ID                    1127
#define IDC_TEST_TIME                   1128
#define IDC_PASS                        1129
#define IDC_FAIL                        1130
#define IDC_TESTED                      1131
#define IDC_PASS2                       1132
#define IDC_PASS_YIELD                  1132
#define IDC_FAIL_YIELD                  1133
#define IDC_LOAD_PROGRAM                1147
#define IDC_START_PAUSE_TEST            1148
#define IDC_DLOG_PARA                   1148
#define IDC_UNLOAD                      1149
#define IDC_DLOG_FUNC                   1149
#define IDC_EXIT_c                      1150
#define IDC_DLOG_LVM                    1150
#define IDC_HELP_c                      1151
#define IDC_DLOG_TOFILE                 1151
#define IDC_COF_MODE                    1152
#define IDC_RADIO3                      1152
#define IDC_EDIT1                       1153
#define IDC_TEMPERATURE                 1153
#define IDC_MANUAL_CONTINUITY           1154
#define IDC_DEBUG_MODE                  1155
#define IDC_DATALOG                     1156
#define IDC_RUNMODE_SELECTED            1157
#define IDC_WAFER_MAP                   1158
#define IDC_PROBECARD_MAP               1159
#define IDC_OI_VERSION                  1160
#define IDC_OI_REV                      1160
#define IDC_USE_LOT_ID_ENTRY            1161
#define IDC_USE_LOT_NUM_ENTRY           1161
#define IDC_LIST1                       1162
#define IDC_SORT_ID_CHK                 1166
#define IDC_SORT_ID_CHECK               1166

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1167
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
