// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "ADC_Test_Out_Vts_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "ADC_Test_Out_Vts" ************/

PATTERN_INITIAL_CONDITIONS( ADC_Test_Out_Vts )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( ADC_Test_Out_Vts )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( ADC_Test_Out_Vts )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( ADC_Test_Out_Vts, -1, 0, vt_NC )
}

PATTERN_VERSIONS( ADC_Test_Out_Vts )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( ADC_Test_Out_Vts )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET3 )
}

PATTERN_USED_VIHHS( ADC_Test_Out_Vts )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( ADC_Test_Out_Vts )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( ADC_Test_Out_Vts )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( ADC_Test_Out_Vts )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( ADC_Test_Out_Vts )
	INSTRUCTIONS( ADC_Test_Out_Vts )
	VAR_UINSTS( ADC_Test_Out_Vts )
	VERSIONS( ADC_Test_Out_Vts )
	USED_TSETS( ADC_Test_Out_Vts )
	USED_VIHHS( ADC_Test_Out_Vts )
	ATTRIBUTES( ADC_Test_Out_Vts )
	HW_REQUIREMENTS( ADC_Test_Out_Vts )
}



/************ data global to this file ************/

LOGIC_VECTORS( ADC_Test_Out_Vts )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "ADC_Test_Out_Vts_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "ADC_Test_Out_Vts_MAG2/ADC_Test_Out_Vts_MAG2.bkm" )
}
