// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "ADC_PAD_IN_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "ADC_PAD_IN" ************/

PATTERN_INITIAL_CONDITIONS( ADC_PAD_IN )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( ADC_PAD_IN )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( ADC_PAD_IN )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( ADC_PAD_IN, -1, 0, vt_NC )
}

PATTERN_VERSIONS( ADC_PAD_IN )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( ADC_PAD_IN )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
}

PATTERN_USED_VIHHS( ADC_PAD_IN )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( ADC_PAD_IN )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( ADC_PAD_IN )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( ADC_PAD_IN )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( ADC_PAD_IN )
	INSTRUCTIONS( ADC_PAD_IN )
	VAR_UINSTS( ADC_PAD_IN )
	VERSIONS( ADC_PAD_IN )
	USED_TSETS( ADC_PAD_IN )
	USED_VIHHS( ADC_PAD_IN )
	ATTRIBUTES( ADC_PAD_IN )
	HW_REQUIREMENTS( ADC_PAD_IN )
}



/************ data global to this file ************/

LOGIC_VECTORS( ADC_PAD_IN )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "ADC_PAD_IN_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "ADC_PAD_IN_MAG2/ADC_PAD_IN_MAG2.bkm" )
}
