// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "CmdTest2_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "CmdTest2" ************/

PATTERN_INITIAL_CONDITIONS( CmdTest2 )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( CmdTest2 )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( CmdTest2 )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( CmdTest2, -1, 0, vt_NC )
}

PATTERN_VERSIONS( CmdTest2 )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( CmdTest2 )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
	PATTERN_USED_TSET( TSET2 )
}

PATTERN_USED_VIHHS( CmdTest2 )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( CmdTest2 )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( CmdTest2 )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( CmdTest2 )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( CmdTest2 )
	INSTRUCTIONS( CmdTest2 )
	VAR_UINSTS( CmdTest2 )
	VERSIONS( CmdTest2 )
	USED_TSETS( CmdTest2 )
	USED_VIHHS( CmdTest2 )
	ATTRIBUTES( CmdTest2 )
	HW_REQUIREMENTS( CmdTest2 )
}



/************ data global to this file ************/

LOGIC_VECTORS( CmdTest2 )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "CmdTest2_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "CmdTest2_MAG2/CmdTest2_MAG2.bkm" )
}
