// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "CmdTest_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "CmdTest" ************/

PATTERN_INITIAL_CONDITIONS( CmdTest )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( CmdTest )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( CmdTest )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( CmdTest, -1, 0, vt_NC )
}

PATTERN_VERSIONS( CmdTest )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( CmdTest )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
}

PATTERN_USED_VIHHS( CmdTest )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( CmdTest )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( CmdTest )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( CmdTest )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( CmdTest )
	INSTRUCTIONS( CmdTest )
	VAR_UINSTS( CmdTest )
	VERSIONS( CmdTest )
	USED_TSETS( CmdTest )
	USED_VIHHS( CmdTest )
	ATTRIBUTES( CmdTest )
	HW_REQUIREMENTS( CmdTest )
}



/************ data global to this file ************/

LOGIC_VECTORS( CmdTest )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "CmdTest_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "CmdTest_MAG2/CmdTest_MAG2.bkm" )
}
