// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "EOT_INIT_CLK_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "EOT_INIT_CLK" ************/

PATTERN_INITIAL_CONDITIONS( EOT_INIT_CLK )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( EOT_INIT_CLK )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( EOT_INIT_CLK )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( EOT_INIT_CLK, -1, 0, vt_NC )
}

PATTERN_VERSIONS( EOT_INIT_CLK )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( EOT_INIT_CLK )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET2 )
}

PATTERN_USED_VIHHS( EOT_INIT_CLK )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( EOT_INIT_CLK )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( EOT_INIT_CLK )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( EOT_INIT_CLK )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( EOT_INIT_CLK )
	INSTRUCTIONS( EOT_INIT_CLK )
	VAR_UINSTS( EOT_INIT_CLK )
	VERSIONS( EOT_INIT_CLK )
	USED_TSETS( EOT_INIT_CLK )
	USED_VIHHS( EOT_INIT_CLK )
	ATTRIBUTES( EOT_INIT_CLK )
	HW_REQUIREMENTS( EOT_INIT_CLK )
}



/************ data global to this file ************/

LOGIC_VECTORS( EOT_INIT_CLK )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "EOT_INIT_CLK_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "EOT_INIT_CLK_MAG2/EOT_INIT_CLK_MAG2.bkm" )
}
