// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "EotStandby_Mode_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "EotStandby_Mode" ************/

PATTERN_INITIAL_CONDITIONS( EotStandby_Mode )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( EotStandby_Mode )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( EotStandby_Mode )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( EotStandby_Mode, -1, 0, vt_NC )
}

PATTERN_VERSIONS( EotStandby_Mode )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( EotStandby_Mode )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET2 )
}

PATTERN_USED_VIHHS( EotStandby_Mode )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( EotStandby_Mode )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( EotStandby_Mode )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( EotStandby_Mode )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( EotStandby_Mode )
	INSTRUCTIONS( EotStandby_Mode )
	VAR_UINSTS( EotStandby_Mode )
	VERSIONS( EotStandby_Mode )
	USED_TSETS( EotStandby_Mode )
	USED_VIHHS( EotStandby_Mode )
	ATTRIBUTES( EotStandby_Mode )
	HW_REQUIREMENTS( EotStandby_Mode )
}



/************ data global to this file ************/

LOGIC_VECTORS( EotStandby_Mode )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "EotStandby_Mode_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "EotStandby_Mode_MAG2/EotStandby_Mode_MAG2.bkm" )
}
