// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "Halver_on_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "Halver_on" ************/

PATTERN_INITIAL_CONDITIONS( Halver_on )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( Halver_on )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( Halver_on )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( Halver_on, -1, 0, vt_NC )
}

PATTERN_VERSIONS( Halver_on )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( Halver_on )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET2 )
}

PATTERN_USED_VIHHS( Halver_on )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( Halver_on )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( Halver_on )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( Halver_on )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( Halver_on )
	INSTRUCTIONS( Halver_on )
	VAR_UINSTS( Halver_on )
	VERSIONS( Halver_on )
	USED_TSETS( Halver_on )
	USED_VIHHS( Halver_on )
	ATTRIBUTES( Halver_on )
	HW_REQUIREMENTS( Halver_on )
}



/************ data global to this file ************/

LOGIC_VECTORS( Halver_on )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "Halver_on_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "Halver_on_MAG2/Halver_on_MAG2.bkm" )
}
