// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _OFF_MARGIN_READ_ARRAY_FF_ALL_H_
#define _OFF_MARGIN_READ_ARRAY_FF_ALL_H_

EXTERN_PATTERN( Off_Margin_Read_Array_FF2 )

#endif
