// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "Off_Margin_Read_Array_FF_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "Off_Margin_Read_Array_FF" ************/

PATTERN_INITIAL_CONDITIONS( Off_Margin_Read_Array_FF )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( Off_Margin_Read_Array_FF )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( Off_Margin_Read_Array_FF )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( Off_Margin_Read_Array_FF, -1, 0, vt_NC )
}

PATTERN_VERSIONS( Off_Margin_Read_Array_FF )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( Off_Margin_Read_Array_FF )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
}

PATTERN_USED_VIHHS( Off_Margin_Read_Array_FF )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( Off_Margin_Read_Array_FF )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( Off_Margin_Read_Array_FF )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( Off_Margin_Read_Array_FF )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( Off_Margin_Read_Array_FF )
	INSTRUCTIONS( Off_Margin_Read_Array_FF )
	VAR_UINSTS( Off_Margin_Read_Array_FF )
	VERSIONS( Off_Margin_Read_Array_FF )
	USED_TSETS( Off_Margin_Read_Array_FF )
	USED_VIHHS( Off_Margin_Read_Array_FF )
	ATTRIBUTES( Off_Margin_Read_Array_FF )
	HW_REQUIREMENTS( Off_Margin_Read_Array_FF )
}



/************ data global to this file ************/

LOGIC_VECTORS( Off_Margin_Read_Array_FF )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "Off_Margin_Read_Array_FF_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "Off_Margin_Read_Array_FF_MAG2/Off_Margin_Read_Array_FF_MAG2.bkm" )
}
