// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "POWER_CHANGE_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "POWER_CHANGE" ************/

PATTERN_INITIAL_CONDITIONS( POWER_CHANGE )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( POWER_CHANGE )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( POWER_CHANGE )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( POWER_CHANGE, -1, 0, vt_NC )
}

PATTERN_VERSIONS( POWER_CHANGE )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( POWER_CHANGE )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET2 )
}

PATTERN_USED_VIHHS( POWER_CHANGE )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( POWER_CHANGE )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( POWER_CHANGE )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( POWER_CHANGE )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( POWER_CHANGE )
	INSTRUCTIONS( POWER_CHANGE )
	VAR_UINSTS( POWER_CHANGE )
	VERSIONS( POWER_CHANGE )
	USED_TSETS( POWER_CHANGE )
	USED_VIHHS( POWER_CHANGE )
	ATTRIBUTES( POWER_CHANGE )
	HW_REQUIREMENTS( POWER_CHANGE )
}



/************ data global to this file ************/

LOGIC_VECTORS( POWER_CHANGE )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "POWER_CHANGE_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "POWER_CHANGE_MAG2/POWER_CHANGE_MAG2.bkm" )
}
