// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "read_normal_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "read_normal" ************/

PATTERN_INITIAL_CONDITIONS( read_normal )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( read_normal )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( read_normal )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( read_normal, -1, 0, vt_NC )
}

PATTERN_VERSIONS( read_normal )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( read_normal )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
}

PATTERN_USED_VIHHS( read_normal )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( read_normal )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( read_normal )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( read_normal )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( read_normal )
	INSTRUCTIONS( read_normal )
	VAR_UINSTS( read_normal )
	VERSIONS( read_normal )
	USED_TSETS( read_normal )
	USED_VIHHS( read_normal )
	ATTRIBUTES( read_normal )
	HW_REQUIREMENTS( read_normal )
}



/************ data global to this file ************/

LOGIC_VECTORS( read_normal )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "read_normal_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "read_normal_MAG2/read_normal_MAG2.bkm" )
}
