// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "Read_CP3_GDFLG_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "Read_CP3_GDFLG" ************/

PATTERN_INITIAL_CONDITIONS( Read_CP3_GDFLG )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( Read_CP3_GDFLG )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( Read_CP3_GDFLG )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( Read_CP3_GDFLG, -1, 0, vt_NC )
}

PATTERN_VERSIONS( Read_CP3_GDFLG )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( Read_CP3_GDFLG )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
}

PATTERN_USED_VIHHS( Read_CP3_GDFLG )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( Read_CP3_GDFLG )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( Read_CP3_GDFLG )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( Read_CP3_GDFLG )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( Read_CP3_GDFLG )
	INSTRUCTIONS( Read_CP3_GDFLG )
	VAR_UINSTS( Read_CP3_GDFLG )
	VERSIONS( Read_CP3_GDFLG )
	USED_TSETS( Read_CP3_GDFLG )
	USED_VIHHS( Read_CP3_GDFLG )
	ATTRIBUTES( Read_CP3_GDFLG )
	HW_REQUIREMENTS( Read_CP3_GDFLG )
}



/************ data global to this file ************/

LOGIC_VECTORS( Read_CP3_GDFLG )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "Read_CP3_GDFLG_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "Read_CP3_GDFLG_MAG2/Read_CP3_GDFLG_MAG2.bkm" )
}
