// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "TS_On_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "TS_On" ************/

PATTERN_INITIAL_CONDITIONS( TS_On )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( TS_On )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( TS_On )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( TS_On, -1, 0, vt_NC )
}

PATTERN_VERSIONS( TS_On )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( TS_On )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
}

PATTERN_USED_VIHHS( TS_On )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( TS_On )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( TS_On )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( TS_On )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( TS_On )
	INSTRUCTIONS( TS_On )
	VAR_UINSTS( TS_On )
	VERSIONS( TS_On )
	USED_TSETS( TS_On )
	USED_VIHHS( TS_On )
	ATTRIBUTES( TS_On )
	HW_REQUIREMENTS( TS_On )
}



/************ data global to this file ************/

LOGIC_VECTORS( TS_On )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "TS_On_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "TS_On_MAG2/TS_On_MAG2.bkm" )
}
