// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef _VREF_EMULATION_TRIM_CODE9_H_
#define _VREF_EMULATION_TRIM_CODE9_H_

EXTERN_PATTERN( Vref_emulation_trim_Code9 )

#endif
