// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "Vref_emulation_trim_Code5_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "Vref_emulation_trim_Code5" ************/

PATTERN_INITIAL_CONDITIONS( Vref_emulation_trim_Code5 )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( Vref_emulation_trim_Code5 )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( Vref_emulation_trim_Code5 )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( Vref_emulation_trim_Code5, -1, 0, vt_NC )
}

PATTERN_VERSIONS( Vref_emulation_trim_Code5 )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( Vref_emulation_trim_Code5 )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
}

PATTERN_USED_VIHHS( Vref_emulation_trim_Code5 )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( Vref_emulation_trim_Code5 )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( Vref_emulation_trim_Code5 )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( Vref_emulation_trim_Code5 )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( Vref_emulation_trim_Code5 )
	INSTRUCTIONS( Vref_emulation_trim_Code5 )
	VAR_UINSTS( Vref_emulation_trim_Code5 )
	VERSIONS( Vref_emulation_trim_Code5 )
	USED_TSETS( Vref_emulation_trim_Code5 )
	USED_VIHHS( Vref_emulation_trim_Code5 )
	ATTRIBUTES( Vref_emulation_trim_Code5 )
	HW_REQUIREMENTS( Vref_emulation_trim_Code5 )
}



/************ data global to this file ************/

LOGIC_VECTORS( Vref_emulation_trim_Code5 )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "Vref_emulation_trim_Code5_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "Vref_emulation_trim_Code5_MAG2/Vref_emulation_trim_Code5_MAG2.bkm" )
}
