// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "Vts_OUT_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "Vts_OUT" ************/

PATTERN_INITIAL_CONDITIONS( Vts_OUT )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( Vts_OUT )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( Vts_OUT )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( Vts_OUT, -1, 0, vt_NC )
}

PATTERN_VERSIONS( Vts_OUT )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( Vts_OUT )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
}

PATTERN_USED_VIHHS( Vts_OUT )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( Vts_OUT )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( Vts_OUT )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( Vts_OUT )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( Vts_OUT )
	INSTRUCTIONS( Vts_OUT )
	VAR_UINSTS( Vts_OUT )
	VERSIONS( Vts_OUT )
	USED_TSETS( Vts_OUT )
	USED_VIHHS( Vts_OUT )
	ATTRIBUTES( Vts_OUT )
	HW_REQUIREMENTS( Vts_OUT )
}



/************ data global to this file ************/

LOGIC_VECTORS( Vts_OUT )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "Vts_OUT_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "Vts_OUT_MAG2/Vts_OUT_MAG2.bkm" )
}
