// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "Write_CP3_GDFLG_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "Write_CP3_GDFLG" ************/

PATTERN_INITIAL_CONDITIONS( Write_CP3_GDFLG )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( Write_CP3_GDFLG )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( Write_CP3_GDFLG )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( Write_CP3_GDFLG, -1, 0, vt_NC )
}

PATTERN_VERSIONS( Write_CP3_GDFLG )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( Write_CP3_GDFLG )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
}

PATTERN_USED_VIHHS( Write_CP3_GDFLG )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( Write_CP3_GDFLG )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( Write_CP3_GDFLG )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( Write_CP3_GDFLG )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( Write_CP3_GDFLG )
	INSTRUCTIONS( Write_CP3_GDFLG )
	VAR_UINSTS( Write_CP3_GDFLG )
	VERSIONS( Write_CP3_GDFLG )
	USED_TSETS( Write_CP3_GDFLG )
	USED_VIHHS( Write_CP3_GDFLG )
	ATTRIBUTES( Write_CP3_GDFLG )
	HW_REQUIREMENTS( Write_CP3_GDFLG )
}



/************ data global to this file ************/

LOGIC_VECTORS( Write_CP3_GDFLG )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "Write_CP3_GDFLG_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "Write_CP3_GDFLG_MAG2/Write_CP3_GDFLG_MAG2.bkm" )
}
