// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "write_normal_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "write_normal" ************/

PATTERN_INITIAL_CONDITIONS( write_normal )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( write_normal )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( write_normal )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( write_normal, -1, 0, vt_NC )
}

PATTERN_VERSIONS( write_normal )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( write_normal )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
}

PATTERN_USED_VIHHS( write_normal )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( write_normal )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( write_normal )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( write_normal )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( write_normal )
	INSTRUCTIONS( write_normal )
	VAR_UINSTS( write_normal )
	VERSIONS( write_normal )
	USED_TSETS( write_normal )
	USED_VIHHS( write_normal )
	ATTRIBUTES( write_normal )
	HW_REQUIREMENTS( write_normal )
}



/************ data global to this file ************/

LOGIC_VECTORS( write_normal )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "write_normal_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "write_normal_MAG2/write_normal_MAG2.bkm" )
}
