// This file has been automatically generated by the pattern compiler.
// DO NOT EDIT!

#ifndef MAGNUM2
#define MAGNUM2
#endif 

#define PATCOM_OUTPUT
#include "tester.h"
#include "XT1_CLK1_MAG2.h"

#ifndef PATTERN_INSTRUCTION
#error PATTERN_INSTRUCTION not #defined ("tester.h" should not have "#pragma once").
#endif



/************ pattern "XT1_CLK1" ************/

PATTERN_INITIAL_CONDITIONS( XT1_CLK1 )   /* C Code to set initial conditions */
{
}

PATTERN_INSTRUCTIONS( XT1_CLK1 )   /* Microcode */
{
}

PATTERN_VAR_UINSTS( XT1_CLK1 )   /* Microinstructions that use/manipulate VAR */
{
	PATTERN_VAR_UINST( XT1_CLK1, -1, 0, vt_NC )
}

PATTERN_VERSIONS( XT1_CLK1 )   /* Version of the compiler output */
{
	PATTERN_VERSION( PATTERN_VAR_GOSUB, 1 )
}

PATTERN_USED_TSETS( XT1_CLK1 )   /* TSETS used by this pattern */
{
	PATTERN_USED_TSET( TSET1 )
}

PATTERN_USED_VIHHS( XT1_CLK1 )   /* VIHH used by this pattern */
{
	PATTERN_USED_VIHH( VIHH1 )
}

PATTERN_ATTRIBUTES( XT1_CLK1 )   /* Pattern attributes */
{
	PATTERN_ATTRIBUTE( LOGIC )
	PATTERN_ATTRIBUTE( SINGLE )
}

PATTERN_HW_REQUIREMENTS( XT1_CLK1 )   /* Hardware requirements */
{
	PATTERN_HW_REQUIREMENT( mag, 2 )
}

PATTERN( XT1_CLK1 )   /* Process the pattern specific information */
{
	INITIAL_CONDITIONS( XT1_CLK1 )
	INSTRUCTIONS( XT1_CLK1 )
	VAR_UINSTS( XT1_CLK1 )
	VERSIONS( XT1_CLK1 )
	USED_TSETS( XT1_CLK1 )
	USED_VIHHS( XT1_CLK1 )
	ATTRIBUTES( XT1_CLK1 )
	HW_REQUIREMENTS( XT1_CLK1 )
}



/************ data global to this file ************/

LOGIC_VECTORS( XT1_CLK1 )   /* Logic vectors prescrambled according to PINASSIGNMENTS */
{
	LOGIC_VECTOR_MAG2( NZ3182, "XT1_CLK1_MAG2/NZ3182.hlh" )
	LOGIC_VECTOR_INDEX( "XT1_CLK1_MAG2/XT1_CLK1_MAG2.bkm" )
}
